import { Geist, Geist_Mono } from "next/font/google";
// import { Toaster } from "react-hot-toast";
import "./globals.css";
import Navbar from "@/components/navbar/page";
import Footer from "@/components/navbar/footer/page";
import ContextProvaider, { FriendsProvidaer } from "@/components/context/ContextProvaider";
import { Toaster } from "react-hot-toast";

// import Context from "@/components/navbar/contexts/context";
// import Contexts from "@/components/contexts/Contexts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      >
      <body className="min-h-full flex flex-col">
           <Navbar></Navbar>
        
       <ContextProvaider>
        
          {children}
       </ContextProvaider>
       <Toaster position="top-right" />
       <Footer></Footer>
      </body>
    </html>
  );
}
